version: "3.6"
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:8888"
    volumes:
      - .:/home/jovyan/work
    container_name: ImageMan
  tensorboard:
      container_name: tensorboard
      build: .
      volumes_from:
        - jupyter
      ports:
        - "6006:6006"
      command:
        - "tensorboard"
        - "--logdir=/home/jovyan/work/default"
